### PR TITLE
fix(sidenav): focus on active

### LINKED ISSUE #649: [Platforms]: SideNav - react tabbing and focus issues

### PR DESCRIPTION
**Pull request by ariellalgilmore**
Closes #649 

if there is an active link then focus should go to that item first on load

- {{new thing}}

**Changed**

- update focus on first item if there is an active link
- add an overflow to the seconary menu
- make sure escape key is handled
- commented out the `lastExpandedState` seemed to be causing errors and not doing much from what I can tell

#### Testing / Reviewing

check on load tabbing

### CODE REVIEW

File: packages/react/src/components/UIShell/components/SideNavMenu.tsx [hunk 1]
```diff
@@ -421,23 +421,23 @@ export const SideNavMenu = React.forwardRef<HTMLElement, SideNavMenuProps>(
...
+      if (primary && currentPrimaryMenu !== uniqueId) {
         setIsExpanded(false);
       } else {
         setIsExpanded(true);
       }
     }, [currentPrimaryMenu]);
 
     // save expanded state before SideNav collapse
-    const [lastExpandedState, setLastExpandedState] = useState(isExpanded);
+    // const [lastExpandedState, setLastExpandedState] = useState(isExpanded); // this seems to be causing issues and not really needed?
```
Comment (alisonjoseph) [inline packages/react/src/components/UIShell/components/SideNavMenu.tsx:432]: Wanted to just check in with @IgnacioBecerra before we remove this.

**Review by alisonjoseph — COMMENTED** [review]
Overall looks good to me, wanted to check in with Ignacio before we totally remove that code, but I think should be ok.

**Review by IgnacioBecerra — APPROVED** [review]
Ignacio approved ™️

**Review by alisonjoseph — APPROVED** [review]
